[tool.poetry]
name = "handsome"
version = "0.1.0"
description = "discord bot for handsome boys"
authors = ["Andrew Herbig <notandrewherbig@gmail.com>"]

[tool.poetry.scripts]
bot = "handsome:main"

[tool.poetry.dependencies]
python = "^3.8"
"discord.py" = {git = "https://github.com/Rapptz/discord.py.git", extras = ["voice"]}
toml = "^0.10.0"
pydantic = "^1.6.1"
devtools = "^0.6"
aioredis = "^1.3.1"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.6.1"
pre-commit = "^2.3.0"
flake8 = "^3.8.4"
pyupgrade = "^2.7.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
